#! /bin/sh

/home/bk/.local/bin/panel &
sxhkd &
mpd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc desktop -f 1
bspc desktop -l monocle; gnome-terminal &
sleep 1;
bspc desktop -f 2
bspc desktop -l monocle; chromium &
sleep 1;
bspc desktop -f 8
bspc desktop -l monocle; chromium -incognito &
sleep 1;


bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrdb -merge /home/bk/.dotfiles/rofioptions
xsetroot -cursor_name left_ptr
feh --bg-scale /mnt/storage/dloads/op.png
