#!/bin/bash

#Array of usernames separated by spaces
users=(BlitzKraft aaronitesWife mythieesWife angrypotato0 The_Dr_B1B)

for i in "${users[@]}"
do
	echo -e "\e[31m\e[1m$i\e[0m"
	output=$(curl -s http://www.reddit.com/user/$i/about.json | tr "," "\n") 
	echo "$output" | grep "link_karma" | tr ": " "\n" | grep -E "[0-9]+" | sed s/"^"/"\tLink Karma: "/	
	echo "$output" | grep "comment_karma" | tr ": " "\n" | grep -E "[0-9]+" | sed s/"^"/"\tComment Karma: "/	
	#echo -e "\n"
	sleep 1
done
